import 'package:flutter/widgets.dart';

class AppLocalizations extends InheritedWidget {
  final String languageCode;

  const AppLocalizations({
    super.key,
    required this.languageCode,
    required super.child,
  });

  static AppLocalizations of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<AppLocalizations>() ??
        const AppLocalizations(languageCode: 'en', child: SizedBox.shrink());
  }

  bool get isVietnamese => languageCode == 'vi';

  String text(String value) {
    if (!isVietnamese) return value;
    return _vi[value] ?? value;
  }

  @override
  bool updateShouldNotify(AppLocalizations oldWidget) {
    return oldWidget.languageCode != languageCode;
  }
}

extension AppLocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String value) => AppLocalizations.of(this).text(value);
}

const Map<String, String> _vi = {
  '6-digit code': 'Mã 6 chữ số',
  'ACCOUNT': 'TÀI KHOẢN',
  'AVAILABLE': 'CÓ THỂ TẢI',
  'Account': 'Tài khoản',
  'Account refreshed.': 'Đã làm mới tài khoản.',
  'Achievements': 'Thành tựu',
  'Accuracy': 'Độ chính xác',
  'AI Review': 'Đánh giá AI',
  'All': 'Tất cả',
  'All writing practice': 'Tất cả bài luyện viết',
  'App Language': 'Ngôn ngữ ứng dụng',
  'Audio is not available yet.': 'Chưa có âm thanh cho mục này.',
  'Audio practice': 'Luyện nghe',
  'Audio feedback in app': 'Âm thanh phản hồi trong ứng dụng',
  'Back': 'Quay lại',
  'Back to Home': 'Về trang chủ',
  'Badges': 'Huy hiệu',
  'Brainy': 'Thông thái',
  '< Back': '< Quay lại',
  '< Back to login': '< Quay lại đăng nhập',
  'Cancel': 'Hủy',
  'Cannot bookmark this vocabulary item yet.': 'Chưa thể lưu mục từ vựng này.',
  'Card Pro': 'Chuyên gia thẻ',
  'Change password': 'Đổi mật khẩu',
  'Change Password': 'Đổi mật khẩu',
  'Clear': 'Xóa',
  'Clear downloads?': 'Xóa bài đã tải?',
  'Clear Offline Downloads': 'Xóa bài học ngoại tuyến',
  'Collector': 'Người sưu tầm',
  'Coming soon': 'Sắp ra mắt',
  'Confirm new password': 'Xác nhận mật khẩu mới',
  'Confirm password': 'Xác nhận mật khẩu',
  'Continue Learning': 'Tiếp tục học',
  'Continue': 'Tiếp tục',
  'Correct': 'Đúng',
  'Correct.': 'Chính xác.',
  'Create Account': 'Tạo tài khoản',
  'Create account': 'Tạo tài khoản',
  'Creating...': 'Đang tạo...',
  'Current lesson': 'Bài học hiện tại',
  'Current password': 'Mật khẩu hiện tại',
  'Daily Goal': 'Mục tiêu ngày',
  'Daily practice': 'Luyện tập hằng ngày',
  'Daily reminder at': 'Nhắc học hằng ngày lúc',
  'Daily reminders are off': 'Nhắc học hằng ngày đang tắt',
  'Dark Mode': 'Chế độ tối',
  'Dark appearance is active here': 'Giao diện tối đang được bật',
  'Dark mode disabled.': 'Đã tắt chế độ tối.',
  'Dark mode enabled.': 'Đã bật chế độ tối.',
  'Day streak': 'Chuỗi ngày',
  'DOWNLOADED': 'ĐÃ TẢI',
  'Downloaded lessons from this device.': 'Bài học đã tải trên thiết bị này.',
  'Easy on the eyes at night': 'Dễ nhìn hơn vào ban đêm',
  'Email': 'Email',
  'Email + Google': 'Email + Google',
  'Email address': 'Địa chỉ email',
  'Email status': 'Trạng thái email',
  'English': 'Tiếng Anh',
  'Enter the 6-digit reset code.': 'Nhập mã đặt lại gồm 6 chữ số.',
  'Enter the code from your email and choose a new password.':
      'Nhập mã trong email và chọn mật khẩu mới.',
  'Enter your email and we will send a 6-digit reset code if the account exists.':
      'Nhập email; nếu tài khoản tồn tại, chúng tôi sẽ gửi mã 6 chữ số.',
  'Evaluating': 'Đang đánh giá',
  'Excellent!': 'Tuyệt vời!',
  'Expected': 'Mẫu đúng',
  'Feedback': 'Nhận xét',
  'Feedback sounds are muted': 'Âm phản hồi đang tắt',
  'First Step': 'Bước đầu tiên',
  'Flashcards': 'Thẻ ghi nhớ',
  'FREE WRITING': 'VIẾT TỰ DO',
  'Forgot password?': 'Quên mật khẩu?',
  'Get Started': 'Bắt đầu',
  'Google': 'Google',
  'Great job! No words need review.': 'Tốt lắm! Không có từ nào cần ôn lại.',
  'Home': 'Trang chủ',
  'History': 'Lịch sử',
  'If the email exists, a reset code has been sent.':
      'Nếu email tồn tại, mã đặt lại đã được gửi.',
  'Japanese': 'Tiếng Nhật',
  'Language preference updated.': 'Đã cập nhật ngôn ngữ.',
  'Last activity today.': 'Hoạt động gần nhất hôm nay.',
  'Last activity yesterday.': 'Hoạt động gần nhất hôm qua.',
  'Learn': 'Học',
  'Learn Japanese, joyfully': 'Học tiếng Nhật thật vui',
  'Learn with Flashcards': 'Học bằng thẻ ghi nhớ',
  'Learner': 'Người học',
  'Learning Snapshot': 'Tổng quan học tập',
  'LEARNING': 'HỌC TẬP',
  'Lesson': 'Bài học',
  'Lesson ID': 'ID bài học',
  'Lesson not available offline': 'Bài học chưa có ngoại tuyến',
  'Lessons': 'Bài học',
  'Light pace': 'Nhịp học nhẹ',
  'Listen and choose': 'Nghe và chọn',
  'Listening': 'Nghe',
  'Listening Practice': 'Luyện nghe',
  'Load a lesson to begin listening practice.':
      'Tải một bài học để bắt đầu luyện nghe.',
  'Load exercises': 'Tải bài tập',
  'Loading flashcards...': 'Đang tải thẻ ghi nhớ...',
  'Loading lessons...': 'Đang tải bài học...',
  'Loading profile...': 'Đang tải hồ sơ...',
  'Loading saved words...': 'Đang tải từ đã lưu...',
  'Loading vocabulary...': 'Đang tải từ vựng...',
  'Local Data': 'Dữ liệu cục bộ',
  'LOCAL DATA': 'DỮ LIỆU CỤC BỘ',
  'Locked': 'Đã khóa',
  'Log Out': 'Đăng xuất',
  'Log out?': 'Đăng xuất?',
  'Manage downloaded lessons': 'Quản lý bài học đã tải',
  'Master Kanji, Hiragana and Katakana with beautifully crafted flashcards.':
      'Ghi nhớ Kanji, Hiragana và Katakana bằng thẻ học trực quan.',
  'MEANING': 'NGHĨA',
  'Name': 'Tên',
  'Need Review': 'Cần ôn',
  'Learned': 'Đã thuộc',
  'New password': 'Mật khẩu mới',
  'Next': 'Tiếp',
  'Next prompt': 'Prompt tiếp theo',
  'No downloaded lessons yet.': 'Chưa có bài học tải xuống.',
  'No flashcards found.': 'Chưa có thẻ ghi nhớ.',
  'No learning activity recorded yet.': 'Chưa có hoạt động học tập nào.',
  'No lessons available to download.': 'Chưa có bài học để tải.',
  'No lessons available yet.': 'Chưa có bài học.',
  'No quiz questions available yet.': 'Chưa có câu hỏi quiz.',
  'No recommendations yet.': 'Chưa có gợi ý.',
  'No saved words match your search.': 'Không có từ đã lưu phù hợp.',
  'No speaking attempts yet.': 'Chưa có lượt luyện nói.',
  'No speaking exercises are available for this lesson yet.':
      'Chưa có bài luyện nói cho bài học này.',
  'No vocabulary found.': 'Chưa có từ vựng.',
  'No words in this group.': 'Không có từ nào trong nhóm này.',
  'No writing exercises are available for this lesson yet.':
      'Chưa có bài luyện viết cho bài học này.',
  'No writing submissions yet.': 'Chưa có bài nộp luyện viết.',
  'Not loaded': 'Chưa tải',
  'Not available': 'Không có dữ liệu',
  'Not quite.': 'Chưa đúng.',
  'Not sure': 'Không chắc',
  'Not verified': 'Chưa xác minh',
  'Notifications': 'Thông báo',
  'Offline': 'Ngoại tuyến',
  'Offline Downloads': 'Tải xuống ngoại tuyến',
  'Offline downloads cleared.': 'Đã xóa bài học ngoại tuyến.',
  'Offline ready': 'Sẵn sàng ngoại tuyến',
  'Onboarding will show again next time.':
      'Hướng dẫn sẽ hiện lại ở lần mở sau.',
  'or continue with': 'hoặc tiếp tục với',
  'Password': 'Mật khẩu',
  'Password, profile, and local data': 'Mật khẩu, hồ sơ và dữ liệu cục bộ',
  'Password changed. Please sign in again.':
      'Đã đổi mật khẩu. Vui lòng đăng nhập lại.',
  'Password reset. Sign in with your new password.':
      'Đã đặt lại mật khẩu. Hãy đăng nhập bằng mật khẩu mới.',
  'Passwords do not match.': 'Mật khẩu không khớp.',
  'Paste a backend lesson id': 'Dán ID bài học từ backend',
  'Pending sync': 'Đang chờ đồng bộ',
  'PENDING SYNC': 'CHỜ ĐỒNG BỘ',
  'Pick a category to start learning': 'Chọn một chủ đề để bắt đầu học',
  'Play audio': 'Phát âm thanh',
  'Play the audio, then select the matching answer.':
      'Phát âm thanh rồi chọn đáp án phù hợp.',
  'Practice saved words': 'Luyện từ đã lưu',
  'Practice sentences': 'Luyện viết câu',
  'Practice with Quizzes': 'Luyện tập bằng quiz',
  'Practice': 'Luyện tập',
  'Practice all your saved words': 'Luyện tập tất cả từ đã lưu',
  'PREFERENCES': 'TÙY CHỌN',
  'Preview': 'Nghe thử',
  'Previous': 'Trước',
  'Privacy & Security': 'Quyền riêng tư & bảo mật',
  'Profile': 'Hồ sơ',
  'Profile could not load.': 'Không thể tải hồ sơ.',
  'Prompt': 'Prompt',
  'Quiz': 'Bài kiểm tra',
  'Quiz completed.': 'Đã hoàn thành bài kiểm tra.',
  'Quiz completed. Pick a lesson to save progress.':
      'Đã hoàn thành bài kiểm tra. Chọn bài học để lưu tiến độ.',
  'Quiz result saved.': 'Đã lưu kết quả quiz.',
  'Quiz result saved locally. Pending sync.':
      'Đã lưu kết quả quiz trên máy. Đang chờ đồng bộ.',
  'Queued for AI review': 'Đã xếp hàng chờ AI đánh giá',
  'Recommended for you': 'Gợi ý cho bạn',
  'Refresh Account': 'Làm mới tài khoản',
  'Reload profile and session data': 'Tải lại hồ sơ và phiên đăng nhập',
  'Reminder Time': 'Giờ nhắc học',
  'Reminder time updated.': 'Đã cập nhật giờ nhắc học.',
  'Remove bookmark': 'Bỏ lưu từ',
  'Remove downloaded lessons from local storage':
      'Xóa bài học đã tải khỏi bộ nhớ cục bộ',
  'Replay recording': 'Phát lại bản ghi',
  'Reset password': 'Đặt lại mật khẩu',
  'Reset Password': 'Đặt lại mật khẩu',
  'Reset the tutorial for the next launch': 'Hiện lại hướng dẫn ở lần mở sau',
  'Resetting...': 'Đang đặt lại...',
  'Restart All': 'Làm lại tất cả',
  'Retry': 'Thử lại',
  'Review Not Learned': 'Ôn từ chưa thuộc',
  'Review Mode': 'Chế độ ôn tập',
  'Sakura': 'Sakura',
  'Sample answer': 'Bài mẫu',
  'Saved': 'Đã lưu',
  'Saved offline. It will sync when you reconnect.':
      'Đã lưu ngoại tuyến. Dữ liệu sẽ đồng bộ khi có mạng.',
  'Saved vocabulary': 'Từ vựng đã lưu',
  'Saved Words': 'Từ đã lưu',
  'Saved words will appear here.': 'Từ đã lưu sẽ xuất hiện ở đây.',
  'Saving...': 'Đang lưu...',
  'Scholar': 'Học giả',
  'Search saved words...': 'Tìm từ đã lưu...',
  'Search words...': 'Tìm từ...',
  'SECURITY': 'BẢO MẬT',
  'See all': 'Xem tất cả',
  'Select a lesson': 'Chọn bài học',
  'Select a lesson to start speaking practice.':
      'Chọn một bài học để bắt đầu luyện nói.',
  'Select a lesson to start writing practice.':
      'Chọn một bài học để bắt đầu luyện viết.',
  'Select Lesson': 'Chọn bài học',
  'Send a new code': 'Gửi mã mới',
  'Send Reset Code': 'Gửi mã đặt lại',
  'Sending...': 'Đang gửi...',
  'SENTENCE': 'CÂU',
  'Session Complete': 'Hoàn thành phiên học',
  'Settings': 'Cài đặt',
  'Show Onboarding Again': 'Hiện hướng dẫn lại',
  'Showing cached lessons': 'Đang hiển thị bài học đã lưu',
  'Showing cached vocabulary': 'Đang hiển thị từ vựng đã lưu',
  'Sign In': 'Đăng nhập',
  'Sign-in': 'Đăng nhập bằng',
  'Sign in to continue learning Japanese':
      'Đăng nhập để tiếp tục học tiếng Nhật',
  'Sign up': 'Đăng ký',
  'Signing in...': 'Đang đăng nhập...',
  'Skip': 'Bỏ qua',
  'Sound Effects': 'Hiệu ứng âm thanh',
  'Sound effects enabled.': 'Đã bật hiệu ứng âm thanh.',
  'Sound effects muted.': 'Đã tắt hiệu ứng âm thanh.',
  'Speaking': 'Nói',
  'Speaking History': 'Lịch sử luyện nói',
  'Speaking Practice': 'Luyện nói',
  'Speaking practice is unavailable offline because this lesson has not been downloaded.':
      'Không thể luyện nói ngoại tuyến vì bài học này chưa được tải.',
  'Speed': 'Tốc độ',
  'Star': 'Ngôi sao',
  'Start your Japanese journey today': 'Bắt đầu hành trình tiếng Nhật hôm nay',
  'Start your first lesson': 'Bắt đầu bài học đầu tiên',
  'Start Flashcard Session': 'Bắt đầu phiên thẻ ghi nhớ',
  'Start Flashcard Session →': 'Bắt đầu phiên thẻ ghi nhớ →',
  'Start recording': 'Bắt đầu ghi âm',
  'Steady pace': 'Nhịp học đều',
  'Stop recording': 'Dừng ghi âm',
  'Study reminders disabled.': 'Đã tắt nhắc học.',
  'Study reminders enabled.': 'Đã bật nhắc học.',
  'Submit': 'Gửi',
  'Submit answer': 'Gửi đáp án',
  'Submit Answer': 'Gửi bài',
  'Submitting': 'Đang gửi',
  'TAP TO FLIP': 'CHẠM ĐỂ LẬT',
  'Test what you know with smart quizzes that adapt to your level.':
      'Kiểm tra kiến thức bằng quiz thông minh theo trình độ của bạn.',
  'There are no offline downloads to clear.':
      'Không có bài học ngoại tuyến để xóa.',
  'Track Your Progress': 'Theo dõi tiến độ',
  'Total': 'Tổng',
  'Transcript': 'Bản chép lời',
  'TRANSLATION': 'DỊCH',
  'Try flashcards': 'Luyện thẻ ghi nhớ',
  'TYPE THE READING': 'NHẬP CÁCH ĐỌC',
  'Type the reading': 'Nhập cách đọc',
  'Unable to load dashboard.': 'Không thể tải bảng học tập.',
  'Untitled lesson': 'Bài học chưa đặt tên',
  'Update the password for this account': 'Cập nhật mật khẩu cho tài khoản này',
  'Update your password for this account.':
      'Cập nhật mật khẩu cho tài khoản này.',
  'Verified': 'Đã xác minh',
  'Vietnamese': 'Tiếng Việt',
  'Vocabulary': 'Từ vựng',
  'VOCABULARY': 'TỪ VỰNG',
  'Welcome back': 'Chào mừng trở lại',
  'Weekly Goal': 'Mục tiêu tuần',
  'Weekly goal updated.': 'Đã cập nhật mục tiêu tuần.',
  'WHAT DOES THIS MEAN?': 'TỪ NÀY NGHĨA LÀ GÌ?',
  'Words': 'Từ',
  'Write an answer before submitting.': 'Hãy viết câu trả lời trước khi gửi.',
  'Write your answer': 'Viết câu trả lời',
  'Writing': 'Viết',
  'Writing answer saved.': 'Đã lưu câu trả lời viết.',
  'Writing History': 'Lịch sử luyện viết',
  'Writing Practice': 'Luyện viết',
  'XP earned': 'XP nhận được',
  'XP Today': 'XP hôm nay',
  'You have completed the quiz': 'Bạn đã hoàn thành bài kiểm tra',
  "You've completed the quiz": 'Bạn đã hoàn thành bài kiểm tra',
  'You can sign back in with this account anytime.':
      'Bạn có thể đăng nhập lại tài khoản này bất cứ lúc nào.',
  'Your answer has been submitted for review.':
      'Câu trả lời của bạn đã được gửi để đánh giá.',
  'YOUR SCORE': 'ĐIỂM CỦA BẠN',
  "Don't have an account? ": 'Chưa có tài khoản? ',
  'A steady reminder at your chosen time.': 'Nhắc đều đặn vào giờ bạn đã chọn.',
  'Afternoon': 'Buổi trưa',
  'Bright taps for correct answers and rewards.':
      'Âm sáng cho đáp án đúng và phần thưởng.',
  'Choose the feedback style and volume.': 'Chọn kiểu âm phản hồi và âm lượng.',
  'Choose when Sakura should nudge you to study.':
      'Chọn khi nào Sakura nên nhắc bạn học.',
  'Custom time': 'Giờ tùy chỉnh',
  'Effect volume': 'Âm lượng hiệu ứng',
  'Evening': 'Buổi tối',
  'Evening review': 'Ôn tập buổi tối',
  'Every day': 'Mỗi ngày',
  'Focus': 'Tập trung',
  'Lunch review': 'Ôn tập giờ trưa',
  'Minimal': 'Tối giản',
  'min': 'phút',
  'Morning': 'Buổi sáng',
  'Morning study': 'Học buổi sáng',
  'Night': 'Ban đêm',
  'Night recap': 'Ôn nhanh ban đêm',
  'Notification schedule updated.': 'Đã cập nhật lịch nhắc học.',
  'Only remind me when my streak needs saving.':
      'Chỉ nhắc khi chuỗi học của tôi cần được giữ.',
  'Pick a time that fits your study rhythm.':
      'Chọn thời điểm hợp với nhịp học của bạn.',
  'Preview sound': 'Nghe thử âm thanh',
  'Sakura pop': 'Sakura vui',
  'Short, quiet feedback for focused sessions.':
      'Âm ngắn và nhẹ cho phiên học tập trung.',
  'Softer cues for night study.': 'Âm dịu hơn khi học buổi tối.',
  'Sound Style': 'Kiểu âm thanh',
  'Sound style updated.': 'Đã cập nhật kiểu âm thanh.',
  'Sound volume updated.': 'Đã cập nhật âm lượng.',
  'Streak rescue': 'Giữ chuỗi học',
  'Study minutes': 'Phút học',
  'Study Notifications': 'Thông báo học tập',
  'Study reminders from Monday to Friday.': 'Nhắc học từ thứ Hai đến thứ Sáu.',
  'Tune the amount of practice you want each week.':
      'Điều chỉnh lượng luyện tập bạn muốn mỗi tuần.',
  'Use the system time picker': 'Dùng bộ chọn giờ hệ thống',
  'Weekdays only': 'Chỉ ngày trong tuần',
  'words': 'từ',
  'Words per day': 'Từ mỗi ngày',
  'Birthday': 'Ngày sinh',
  'Display name': 'Tên hiển thị',
  'Edit profile': 'Chỉnh sửa hồ sơ',
  'Female': 'Nữ',
  'Gender': 'Giới tính',
  'Male': 'Nam',
  'Non-binary': 'Phi nhị nguyên giới',
  'Not set': 'Chưa đặt',
  'Prefer not to say': 'Không muốn trả lời',
  'Profile updated.': 'Đã cập nhật hồ sơ.',
  'Remove avatar': 'Xóa ảnh đại diện',
  'Save profile': 'Lưu hồ sơ',
  'Upload avatar': 'Tải ảnh đại diện',
};
